#!/bin/bash
# Cloudflare DNS + SSL configuration for studios.zanzibaba.com
# Generated by Zanzibaba Studios deployment automation
#
# PREREQUISITES:
#   1. Cloudflare account with zanzibaba.com added to your account
#   2. Cloudflare API token with DNS edit + SSL edit permissions
#      https://dash.cloudflare.com/profile/api-tokens
#   3. Set env vars:
#      export CF_API_TOKEN="<your-token>"
#      export CF_ZONE_ID="<zone-id-for-zanzibaba.com>"
#      export CF_TARGET="<vercel-cname-or-server-ip>"
#
# USAGE:
#   bash cloudflare-config.sh

set -e

if [ -z "$CF_API_TOKEN" ] || [ -z "$CF_ZONE_ID" ] || [ -z "$CF_TARGET" ]; then
  echo "ERROR: Set CF_API_TOKEN, CF_ZONE_ID, and CF_TARGET environment variables"
  echo "  export CF_API_TOKEN=\"<token>\""
  echo "  export CF_ZONE_ID=\"<zone-id>\""
  echo "  export CF_TARGET=\"cname.vercel-dns.com\""
  exit 1
fi

ZONE=$CF_ZONE_ID
API="https://api.cloudflare.com/client/v4"
AUTH="Authorization: Bearer $CF_API_TOKEN"

echo "=== Configuring Cloudflare for studios.zanzibaba.com ==="
echo ""

# ============ 1. DNS RECORDS ============
echo ">>> [1/7] Adding CNAME record for studios subdomain"

# Detect if target is IP (A record) or hostname (CNAME)
if [[ "$CF_TARGET" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  RECORD_TYPE="A"
  CONTENT="$CF_TARGET"
else
  RECORD_TYPE="CNAME"
  CONTENT="$CF_TARGET"
fi

curl -s -X POST "$API/zones/$ZONE/dns_records" \
  -H "$AUTH" -H "Content-Type: application/json" \
  --data "{
    \"type\": \"$RECORD_TYPE\",
    \"name\": \"studios\",
    \"content\": \"$CONTENT\",
    \"ttl\": 1,
    \"proxied\": true,
    \"comment\": \"Zanzibaba Studios - auto-configured\"
  }" | python3 -c "import sys, json; d = json.load(sys.stdin); print('    OK' if d.get('success') else '    FAIL: ' + str(d.get('errors')))"

# ============ 2. SSL — Full (Strict) ============
echo ">>> [2/7] Setting SSL to Full (Strict)"
curl -s -X PATCH "$API/zones/$ZONE/settings/ssl" \
  -H "$AUTH" -H "Content-Type: application/json" \
  --data '{ "value": "full" }' | python3 -c "import sys, json; d = json.load(sys.stdin); print('    OK' if d.get('success') else '    FAIL')"

# ============ 3. ALWAYS USE HTTPS ============
echo ">>> [3/7] Enabling Always Use HTTPS"
curl -s -X PATCH "$API/zones/$ZONE/settings/always_use_https" \
  -H "$AUTH" -H "Content-Type: application/json" \
  --data '{ "value": "on" }' | python3 -c "import sys, json; d = json.load(sys.stdin); print('    OK' if d.get('success') else '    FAIL')"

# ============ 4. AUTO HTTPS REWRITES ============
echo ">>> [4/7] Enabling Auto HTTPS Rewrites"
curl -s -X PATCH "$API/zones/$ZONE/settings/automatic_https_rewrites" \
  -H "$AUTH" -H "Content-Type: application/json" \
  --data '{ "value": "on" }' | python3 -c "import sys, json; d = json.load(sys.stdin); print('    OK' if d.get('success') else '    FAIL')"

# ============ 5. BROTLI ============
echo ">>> [5/7] Enabling Brotli compression"
curl -s -X PATCH "$API/zones/$ZONE/settings/brotli" \
  -H "$AUTH" -H "Content-Type: application/json" \
  --data '{ "value": "on" }' | python3 -c "import sys, json; d = json.load(sys.stdin); print('    OK' if d.get('success') else '    FAIL')"

# ============ 6. HTTP/3 (QUIC) ============
echo ">>> [6/7] Enabling HTTP/3"
curl -s -X PATCH "$API/zones/$ZONE/settings/http3" \
  -H "$AUTH" -H "Content-Type: application/json" \
  --data '{ "value": "on" }' | python3 -c "import sys, json; d = json.load(sys.stdin); print('    OK' if d.get('success') else '    FAIL')"

# ============ 7. CACHING + MINIFY ============
echo ">>> [7/7] Configuring caching and minification"
curl -s -X PATCH "$API/zones/$ZONE/settings/cache_level" \
  -H "$AUTH" -H "Content-Type: application/json" \
  --data '{ "value": "aggressive" }' | python3 -c "import sys, json; d = json.load(sys.stdin); print('    Cache level: OK' if d.get('success') else '    FAIL')"

curl -s -X PATCH "$API/zones/$ZONE/settings/minify" \
  -H "$AUTH" -H "Content-Type: application/json" \
  --data '{ "value": { "html": "on", "css": "on", "js": "on" } }' | python3 -c "import sys, json; d = json.load(sys.stdin); print('    Minify: OK' if d.get('success') else '    FAIL')"

echo ""
echo "=== Cloudflare configuration complete ==="
echo ""
echo "Verification commands:"
echo "  dig +short studios.zanzibaba.com"
echo "  curl -I https://studios.zanzibaba.com/"
echo "  curl -I --http3 https://studios.zanzibaba.com/"
